#
# SPDX-FileCopyrightText: 2026 The Semantifyr Authors
#
# SPDX-License-Identifier: EPL-2.0
#

appender.console.type=Console
appender.console.name=STDOUT
appender.console.target=SYSTEM_OUT
appender.console.layout.type=PatternLayout
appender.console.layout.pattern=[%-5level] %d{HH:mm:ss.SSS} %c{1} - %msg%n

rootLogger.level=warn
rootLogger.appenderRef.stdout.ref=STDOUT

logger.semantifyr.name=hu.bme.mit.semantifyr.live
logger.semantifyr.level=warn

logger.benchmark.name=hu.bme.mit.semantifyr.live.backend.benchmark
logger.benchmark.level=info

logger.ktor.name=io.ktor
logger.ktor.level=warn

logger.netty.name=io.netty
logger.netty.level=warn
