<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="oxsts" nsURI="http://www.bme.hu/mit/2023/oxsts" nsPrefix="oxsts">
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="OxstsModelPackage" eSuperTypes="#//Namespace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//ImportStatement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" upperBound="-1"
        eType="#//Declaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransitionDeclaration" eSuperTypes="#//ParametricDeclaration #//RedefinableDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="branches" lowerBound="1"
        upperBound="-1" eType="#//SequenceOperation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" lowerBound="1" eType="#//TransitionKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceOperation" eSuperTypes="#//Namespace #//Operation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="steps" upperBound="-1"
        eType="#//Operation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" abstract="true" eSuperTypes="#//Element"/>
  <eClassifiers xsi:type="ecore:EClass" name="HavocOperation" eSuperTypes="#//Operation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssignmentOperation" eSuperTypes="#//Operation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" lowerBound="1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChoiceOperation" eSuperTypes="#//Operation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="else" eType="#//SequenceOperation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="branches" lowerBound="1"
        upperBound="-1" eType="#//SequenceOperation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureDeclaration" eSuperTypes="#//DomainDeclaration #//Namespace #//RedefinableDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superset" eType="#//FeatureDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//TypeDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="multiplicity" eType="#//Multiplicity"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="opposite" eType="#//FeatureDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" lowerBound="1" eType="#//FeatureKind"
        defaultValueLiteral="REFERENCE"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="innerFeatures" upperBound="-1"
        eType="#//FeatureDeclaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassDeclaration" eSuperTypes="#//TopLevelDeclaration #//Namespace #//TypeDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superTypes" upperBound="-1"
        eType="#//ClassDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        eType="#//Declaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InlineCall" eSuperTypes="#//InlineOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="callExpression" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" eSuperTypes="#//Element"/>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralExpression" abstract="true" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralInteger" eSuperTypes="#//LiteralExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralBoolean" eSuperTypes="#//LiteralExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralNothing" eSuperTypes="#//LiteralExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceExpression" abstract="true"
      eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="OperatorExpression" abstract="true"
      eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="AssumptionOperation" eSuperTypes="#//Operation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Multiplicity" abstract="true" eSuperTypes="#//Element"/>
  <eClassifiers xsi:type="ecore:EClass" name="SelfReference" eSuperTypes="#//DirectReferenceExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="class" eType="#//ClassDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementReference" eSuperTypes="#//DirectReferenceExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" lowerBound="1"
        eType="#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InlineOperation" abstract="true" eSuperTypes="#//Operation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Namespace" abstract="true" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="IfOperation" eSuperTypes="#//Operation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="#//SequenceOperation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="else" eType="#//SequenceOperation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InlineIfOperation" eSuperTypes="#//InlineOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="#//SequenceOperation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="else" eType="#//SequenceOperation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumLiteral" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnumDeclaration" eSuperTypes="#//Namespace #//TopLevelDeclaration #//TypeDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="literals" lowerBound="1"
        upperBound="-1" eType="#//EnumLiteral" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyDeclaration" eSuperTypes="#//ParametricDeclaration #//RedefinableDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" eType="#//TypeDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XSTS" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enums" upperBound="-1"
        eType="#//EnumDeclaration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mainTransition" lowerBound="1"
        eType="#//TransitionDeclaration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" lowerBound="1"
        eType="#//PropertyDeclaration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//VariableDeclaration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initTransition" lowerBound="1"
        eType="#//TransitionDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableDeclaration" eSuperTypes="#//Declaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//DomainDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="control" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="multiplicity" eType="#//Multiplicity"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TargetDeclaration" eSuperTypes="#//ClassDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="RecordDeclaration" eSuperTypes="#//Namespace #//TopLevelDeclaration #//TypeDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        eType="#//Declaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImportStatement" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="importedPackage" lowerBound="1"
        eType="#//OxstsModelPackage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Association" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="1"
        eType="#//FeatureDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instances" upperBound="-1"
        eType="#//Instance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PatternDeclaration" eSuperTypes="#//Namespace #//TopLevelDeclaration #//ParametricDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bodies" upperBound="-1"
        eType="#//Conjunction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Conjunction" eSuperTypes="#//Element"/>
  <eClassifiers xsi:type="ecore:EEnum" name="TransitiveClosureKind">
    <eLiterals name="None"/>
    <eLiterals name="WithoutSelf" value="1"/>
    <eLiterals name="IncludeSelf" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterDeclaration" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//TypeDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="multiplicity" eType="#//Multiplicity"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryOperator" abstract="true" eSuperTypes="#//OperatorExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryOperator" abstract="true" eSuperTypes="#//OperatorExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UnaryOp">
    <eLiterals name="PLUS"/>
    <eLiterals name="MINUS" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ArithmeticOp">
    <eLiterals name="ADD"/>
    <eLiterals name="SUB" value="1" literal="SUB"/>
    <eLiterals name="MUL" value="2"/>
    <eLiterals name="DIV" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComparisonOperator" eSuperTypes="#//BinaryOperator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" lowerBound="1" eType="#//ComparisonOp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArithmeticBinaryOperator" eSuperTypes="#//BinaryOperator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" lowerBound="1" eType="#//ArithmeticOp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArithmeticUnaryOperator" eSuperTypes="#//UnaryOperator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" lowerBound="1" eType="#//UnaryOp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NegationOperator" eSuperTypes="#//UnaryOperator"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ComparisonOp">
    <eLiterals name="LESS"/>
    <eLiterals name="LESS_EQ" value="1"/>
    <eLiterals name="GREATER" value="2"/>
    <eLiterals name="GREATER_EQ" value="3"/>
    <eLiterals name="EQ" value="4"/>
    <eLiterals name="NOT_EQ" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnboundedMultiplicity" eSuperTypes="#//Multiplicity"/>
  <eClassifiers xsi:type="ecore:EClass" name="DefiniteMultiplicity" eSuperTypes="#//Multiplicity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanOperator" eSuperTypes="#//BinaryOperator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" lowerBound="1" eType="#//BooleanOp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BooleanOp">
    <eLiterals name="AND" value="4"/>
    <eLiterals name="OR" value="5"/>
    <eLiterals name="XOR" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationSuffixExpression" eSuperTypes="#//PostfixUnaryExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="member" lowerBound="1"
        eType="#//NamedElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndexingSuffixExpression" eSuperTypes="#//PostfixUnaryExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="index" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallSuffixExpression" eSuperTypes="#//PostfixUnaryExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="#//Argument" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayLiteral" eSuperTypes="#//LiteralExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Argument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" eType="#//ParameterDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralReal" eSuperTypes="#//LiteralExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionDeclaration" eSuperTypes="#//ParametricDeclaration #//TopLevelDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" eType="#//TypeDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParametricDeclaration" abstract="true"
      eSuperTypes="#//Declaration #//Namespace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//ParameterDeclaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TopLevelDeclaration" abstract="true"
      eSuperTypes="#//Declaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="Declaration" abstract="true" eSuperTypes="#//NamedElement #//AnnotatedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnnotationDeclaration" eSuperTypes="#//TopLevelDeclaration #//ParametricDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="Annotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaration" lowerBound="1"
        eType="#//AnnotationDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="#//Argument" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TransitionKind">
    <eLiterals name="TRAN"/>
    <eLiterals name="ENV" value="1"/>
    <eLiterals name="INIT" value="2"/>
    <eLiterals name="HAVOC" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnnotationContainer" eSuperTypes="#//Declaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
        eType="#//Annotation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnnotatedElement" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotation" eType="#//AnnotationContainer"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FeatureKind">
    <eLiterals name="REFERENCE"/>
    <eLiterals name="CONTAINMENT" value="1"/>
    <eLiterals name="CONTAINER" value="2"/>
    <eLiterals name="DERIVED" value="3"/>
    <eLiterals name="FEATURE" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralString" eSuperTypes="#//LiteralExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataTypeDeclaration" eSuperTypes="#//TopLevelDeclaration #//TypeDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypeDeclaration" abstract="true" eSuperTypes="#//Declaration #//DomainDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="DomainDeclaration" abstract="true" eSuperTypes="#//Declaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="DirectReferenceExpression" abstract="true"
      eSuperTypes="#//ReferenceExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="PostfixUnaryExpression" abstract="true"
      eSuperTypes="#//ReferenceExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="primary" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InlineSeqFor" eSuperTypes="#//InlineForOperation"/>
  <eClassifiers xsi:type="ecore:EClass" name="InlineChoiceFor" eSuperTypes="#//InlineForOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="else" eType="#//SequenceOperation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractForOperation" abstract="true"
      eSuperTypes="#//Operation #//Namespace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="loopVariable" eType="#//VariableDeclaration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rangeExpression" lowerBound="1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="#//SequenceOperation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalVarDeclarationOperation" eSuperTypes="#//VariableDeclaration #//Operation"/>
  <eClassifiers xsi:type="ecore:EClass" name="ForOperation" eSuperTypes="#//AbstractForOperation"/>
  <eClassifiers xsi:type="ecore:EClass" name="InlineForOperation" abstract="true"
      eSuperTypes="#//AbstractForOperation #//InlineOperation"/>
  <eClassifiers xsi:type="ecore:EClass" name="RangeExpression" eSuperTypes="#//BinaryOperator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exclusive" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralInfinity" eSuperTypes="#//LiteralExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Instance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Instance" containment="true" eOpposite="#//Instance/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domain" lowerBound="1"
        eType="#//DomainDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Instance"
        eOpposite="#//Instance/children"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//InlinedOxsts"
        eOpposite="#//InlinedOxsts/rootInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associations" upperBound="-1"
        eType="#//Association" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variableMappings" upperBound="-1"
        eType="#//VariableMapping" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssociationValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="VariableMapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="original" lowerBound="1"
        eType="#//VariableDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actual" lowerBound="1"
        eType="#//VariableDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RedefinableDeclaration" eSuperTypes="#//Declaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="redefine" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="redefined" eType="#//RedefinableDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InlinedOxsts" eSuperTypes="#//DomainDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="initTransition" lowerBound="1"
        eType="#//TransitionDeclaration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mainTransition" lowerBound="1"
        eType="#//TransitionDeclaration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" lowerBound="1"
        eType="#//PropertyDeclaration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//VariableDeclaration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classDeclaration" lowerBound="1"
        eType="#//ClassDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootInstance" eType="#//Instance"
        containment="true" eOpposite="#//Instance/model"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootFeature" eType="#//FeatureDeclaration"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
