/*
 * generated by Xtext 2.36.0
 */
package hu.bme.mit.semantifyr.xsts.lang.validation;


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class XstsValidator extends AbstractXstsValidator {

}
