/*
 * generated by Xtext 2.36.0
 */
package hu.bme.mit.semantifyr.cex.lang;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CexStandaloneSetup extends CexStandaloneSetupGenerated {

	public static void doSetup() {
		new CexStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
