/*
 * generated by Xtext 2.32.0
 */
package hu.bme.mit.gamma.oxsts.lang.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class OxstsProposalProvider extends AbstractOxstsProposalProvider {
}
