#
# SPDX-FileCopyrightText: 2026 The Semantifyr Authors
#
# SPDX-License-Identifier: EPL-2.0
#

appender.console.type=Console
appender.console.name=STDOUT
appender.console.target=SYSTEM_OUT
appender.console.layout.type=PatternLayout
appender.console.layout.pattern=[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] [%X{sessionId}] [%X{requestId}] %c{1} - %msg%n

rootLogger.level=info
rootLogger.appenderRef.stdout.ref=STDOUT

logger.semantifyr.name=hu.bme.mit.semantifyr.live
logger.semantifyr.level=info

logger.ktor.name=io.ktor
logger.ktor.level=warn

logger.netty.name=io.netty
logger.netty.level=warn

logger.xtext.name=org.eclipse.xtext
logger.xtext.level=warn

logger.emf.name=org.eclipse.emf
logger.emf.level=warn

logger.lsp4j.name=org.eclipse.lsp4j
logger.lsp4j.level=warn
