#
# SPDX-FileCopyrightText: 2026 The Semantifyr Authors
#
# SPDX-License-Identifier: EPL-2.0
#

appender.console.type=Console
appender.console.name=Console
appender.console.target=SYSTEM_OUT
appender.console.layout.type=PatternLayout
appender.console.layout.pattern=[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] [%X{sessionId}] %c{1} - %msg%n

rootLogger.level=info
rootLogger.appenderRef.console.ref=Console

logger.semantifyr.name=hu.bme.mit.semantifyr.live
logger.semantifyr.level=info

logger.ktor.name=io.ktor
logger.ktor.level=warn

logger.netty.name=io.netty
logger.netty.level=warn
