/*
 * generated by Xtext 2.36.0
 */
package hu.bme.mit.semantifyr.cex.lang.formatting2;

import hu.bme.mit.semantifyr.cex.lang.cex.Cex;
import hu.bme.mit.semantifyr.cex.lang.cex.XstsState;
import org.eclipse.xtext.formatting2.AbstractJavaFormatter;
import org.eclipse.xtext.formatting2.IFormattableDocument;

public class CexFormatter extends AbstractJavaFormatter {

	protected void format(Cex cex, IFormattableDocument doc) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (XstsState xstsState : cex.getStates()) {
			doc.format(xstsState);
		}
	}

	protected void format(XstsState xstsState, IFormattableDocument doc) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		doc.format(xstsState.getState());
	}
	
	// TODO: implement for ExplState
}
