/*
 * generated by Xtext 2.32.0
 */
package hu.bme.mit.gamma.oxsts.lang;


import org.eclipse.xtext.naming.IQualifiedNameConverter;
import org.eclipse.xtext.naming.IQualifiedNameProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class OxstsRuntimeModule extends AbstractOxstsRuntimeModule {
    public Class<? extends IQualifiedNameConverter> bindIQualifiedNameConverter() {
        return OxstsQualifiedNameConverter.class;
    }
}

class OxstsQualifiedNameConverter extends IQualifiedNameConverter.DefaultImpl {
    @Override
    public String getDelimiter() {
        return "::";
    }
}
