/*
 * generated by Xtext 2.32.0
 */
package hu.bme.mit.gamma.oxsts.lang;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class OxstsRuntimeModule extends AbstractOxstsRuntimeModule {
}
