/*
 * generated by Xtext 2.36.0
 */
package hu.bme.mit.semantifyr.cex.lang;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CexRuntimeModule extends AbstractCexRuntimeModule {
}
