/*
 * SPDX-FileCopyrightText: 2025-2026 The Semantifyr Authors
 *
 * SPDX-License-Identifier: EPL-2.0
 */

import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

export default {
  learnSidebar: [{ type: 'autogenerated', dirName: 'learn' }],
  developSidebar: [{ type: 'autogenerated', dirName: 'develop' }],
} satisfies SidebarsConfig;
