package hu.bme.mit.semantifyr.gradle

plugins {
    id("hu.bme.mit.semantifyr.gradle.conventions.jvm")
}

val xtextGenerated by configurations.creating {
    isCanBeConsumed = false
    isCanBeResolved = true
}

val xtextGenPath = "src/main/xtext-gen"
val xtextTestFixtureGenPath = "src/testFixtures/xtext-gen"

sourceSets {
    main {
        java.srcDir(xtextGenPath)
        resources.srcDir(xtextGenPath)
    }
    testFixtures {
        java.srcDir(xtextTestFixtureGenPath)
        resources.srcDir(xtextTestFixtureGenPath)
    }
}

tasks {
    val syncXtextGeneratedSources by tasks.creating(Sync::class) {
        from(xtextGenerated)
        into(xtextGenPath)
    }

    for (taskName in listOf("compileJava", "processResources", "generateEclipseSourceFolders")) {
        tasks.named(taskName) {
            dependsOn(syncXtextGeneratedSources)
        }
    }

    clean {
        delete(xtextGenPath)
    }
}
