/*
 * SPDX-FileCopyrightText: 2023-2024 The Semantifyr Authors
 *
 * SPDX-License-Identifier: EPL-2.0
 */

package hu.bme.mit.semantifyr.gradle

import org.gradle.accessors.dm.LibrariesForLibs

plugins {
    id("hu.bme.mit.semantifyr.gradle.conventions.jvm")
}

val ideGeneratedClasspath by configurations.creating {
    isCanBeConsumed = false
    isCanBeResolved = true
}

val libs = the<LibrariesForLibs>()

val extension = extensions.create("xtext", XtextIdePluginConfiguration::class.java).apply {
    genPath.convention(layout.projectDirectory.dir("src/main/xtext-gen"))
}

dependencies {
    api(libs.xtext.ide)
}

sourceSets {
    main {
        java.srcDir(extension.genPath)
        resources.srcDir(extension.genPath)
    }
}

tasks {
    val cloneIdeGenerated by registering(Sync::class) {
        inputs.files(ideGeneratedClasspath)

        from(ideGeneratedClasspath.asFileTree)
        into(extension.genPath)
    }

    compileJava {
        inputs.files(cloneIdeGenerated)
    }

    processResources {
        inputs.files(cloneIdeGenerated)
    }

    clean {
        delete(extension.genPath)
    }
}

interface XtextIdePluginConfiguration {
    val genPath: DirectoryProperty
}
