/*
 * generated by Xtext 2.36.0
 */
package hu.bme.mit.semantifyr.cex.lang.formatting2;

import org.eclipse.xtext.formatting2.AbstractJavaFormatter;

public class CexFormatter extends AbstractJavaFormatter {

}
