/*
 * generated by Xtext 2.32.0
 */
package hu.bme.mit.gamma.oxsts.lang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class OxstsUiModule extends AbstractOxstsUiModule {

	public OxstsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
