#
# SPDX-FileCopyrightText: 2025 The Semantifyr Authors
#
# SPDX-License-Identifier: EPL-2.0
#

rootLogger.level=INFO
rootLogger.appenderRef.file.ref=FileAppender

appender.file.name=FileAppender
appender.file.type=File
appender.file.fileName=xsts.lsp.log
appender.file.layout.type=PatternLayout
appender.file.layout.pattern=%p\t%d{ISO8601}\t%r\t%c\t[%t]\t%m%n
