# SPDX-FileCopyrightText: 2023-2024 The Semantifyr Authors
#
# SPDX-License-Identifier: EPL-2.0

name: Continuous Integration
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CI: true
jobs:
  build:
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: 25
        distribution: adopt
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
    - name: Gradle build
      shell: bash
      run: ./gradlew build
    - name: Bundle Extension
      shell: bash
      run: ./gradlew bundleExtension
    - name: Upload Artifacts
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: actions/upload-artifact@v7
      with:
        path: |
          **/build/vscode/
          **/build/distributions/
          **/build/reports/
          **/build/test-results/

  reuse-check:
    name: REUSE Compliance Check
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v6
